---

root: true

plugins:
  - functional

extends:
  - airbnb
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"

parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: latest

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

ignorePatterns:
  - dist

rules:
  functional/functional-parameters: 0
  functional/immutable-data: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/no-throw-statement: 0
  functional/no-try-statement: 0
  import/extensions: 0
  jsx-a11y/label-has-associated-control:
    - 2
    - assert: either
  no-console: 0
  object-curly-newline: 0
  react/function-component-definition:
    - 1
    - namedComponents: arrow-function
  react/prop-types: 0
